sudo: required

language: java
jdk:
  - oraclejdk8

services:
    - docker

cache:
    directories:
        - $HOME/.m2
        - $HOME/apache-maven-3.3.9

before_cache:
    - rm -rf $HOME/.m2/repository/com/alvexcore

before_install:
    - ln -s ./scripts/mvn.sh ./mvnw
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then base64 -d <<< $MAVEN_DEPLOY_SETTINGS | tar -xz -C $HOME; fi'

install: true

script:
    - rm -rf $HOME/.m2/repository/com/alvexcore
    - ./mvnw -D package.all clean package
    - ./mvnw docker:build &> /dev/null
    - export CONTAINER_NAME=$( docker run -d -p 127.0.0.1:8080:8080 alvex )
    - ./scripts/run_integration_tests.sh docker

after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./mvnw -D package.all deploy; fi'

notifications:
  email:
    recipients:
      - alvex-build@itdhq.com 
    on_success: change
    on_failure: always
