sudo: false

language: java
jdk:
  - oraclejdk8

cache:
    directories:
        - $HOME/.m2
        - $HOME/apache-maven-3.3.9

before_script:
    - wget https://raw.githubusercontent.com/ITDSystems/alvex-common/master/scripts/mvn.sh
    - chmod +x mvn.sh
    - echo "MAVEN_OPTS='-Xmx3g -XX:MaxPermSize=512m'" > ~/.mavenrc


script:
    - rm -rf $HOME/.m2/repository/com/alvexcore
    - ./mvn.sh clean package
    - ./mvn.sh clean package -P make-jar
    - rm -rf $HOME/.m2/repository/com/alvexcore
    - ./mvn.sh -f packaging_pom.xml -P orgchart,uploader,inform-policy,infavorites-document-association  clean package
