sudo: false

language: java
jdk:
  - oraclejdk8

cache:
    directories:
        - $HOME/.m2
        - $HOME/apache-maven-3.3.9

before_install:
    - ln -s ./scripts/mvn.sh ./mvnw

install: true

script:
    - rm -rf $HOME/.m2/repository/com/alvexcore
    - ./mvnw -D package.all clean package

after_success:
    - ./mvnw -D package.all deploy

notifications:
  email:
    recipients:
      - alvex-build@itdhq.com 
    on_success: change
    on_failure: always
